// Stage 4 — Turn src/data/pages/*.json + src/data/site.json into real Astro pages.
//
// For each page JSON, creates src/pages/<route>/index.astro that imports Layout
// and a small set of section components, then renders content from the JSON.

import fs from 'node:fs/promises';
import path from 'node:path';
import { DATA, DATA_PAGES, SRC_PAGES, routeFromSlug } from './config.mjs';

const siteJson = JSON.parse(
  await fs.readFile(path.join(DATA, 'site.json'), 'utf8').catch(() => '{}'),
);

function escape(str = '') {
  return String(str).replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function renderSectionsAstro(sections) {
  return sections
    .map((s, i) => {
      const headings = s.headings
        .map((h) => `<${h.tag}>{\`${escape(h.text)}\`}</${h.tag}>`)
        .join('\n    ');
      const paragraphs = s.paragraphs
        .map((p) => `<p>{\`${escape(p)}\`}</p>`)
        .join('\n    ');
      const images = s.images
        .map(
          (img) =>
            `<img src=${JSON.stringify(img.src)} alt=${JSON.stringify(img.alt)} loading="lazy" decoding="async" />`,
        )
        .join('\n    ');
      const ctas = s.ctas
        .map(
          (c) =>
            `<a href=${JSON.stringify(c.href)} class="btn">{\`${escape(c.text)}\`}</a>`,
        )
        .join('\n    ');
      return `
  <section class="sec sec-${i}">
    ${headings}
    ${paragraphs}
    ${images}
    ${ctas}
  </section>`;
    })
    .join('\n');
}

function renderPage(page) {
  const { meta } = page;
  const jsonLdScripts = (meta.jsonLd || [])
    .map((j) => `<script type="application/ld+json" set:html={${JSON.stringify(j)}}></script>`)
    .join('\n');
  return `---
// Auto-generated by tools/generate.mjs — do not edit directly.
// Source: src/data/pages/${page.slug}.json
import Layout from '${path.posix.relative(
    path.posix.dirname(`src/pages${page.route}index.astro`),
    'src/layouts/Layout.astro',
  ) || '../layouts/Layout.astro'}';
---

<Layout title={${JSON.stringify(meta.title)}} description={${JSON.stringify(meta.description)}} canonical={${JSON.stringify(meta.canonical)}} ogImage={${JSON.stringify(meta.ogImage || '')}}>
${jsonLdScripts}
<main>${renderSectionsAstro(page.sections)}
</main>
</Layout>
`;
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

const files = (await fs.readdir(DATA_PAGES)).filter((f) => f.endsWith('.json'));
let generated = 0;
for (const f of files) {
  const page = JSON.parse(await fs.readFile(path.join(DATA_PAGES, f), 'utf8'));
  const route = routeFromSlug(page.slug);
  const outDir =
    route === ''
      ? SRC_PAGES
      : path.join(SRC_PAGES, route);
  const outFile =
    route === ''
      ? path.join(SRC_PAGES, 'index.astro')
      : path.join(outDir, 'index.astro');
  await ensureDir(path.dirname(outFile));
  await fs.writeFile(outFile, renderPage(page), 'utf8');
  console.log(`[generate] ${page.slug} -> ${path.relative(SRC_PAGES, outFile)}`);
  generated++;
}

console.log(`\n[generate] ${generated} pages written under src/pages/.`);
